/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package mexs {

    [Bindable]
    [RemoteClass(alias="mexs.Terminal")]
    public class Terminal extends TerminalBase {
    }
}