/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (EmployeeRole.as).
 */

package mexs {

    import flash.events.EventDispatcher;
    import flash.net.FileReference;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import flash.utils.getQualifiedClassName;
    import mx.collections.ListCollectionView;
    import mx.core.IUID;
    import mx.utils.UIDUtil;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;
    import org.granite.tide.IEntity;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;
    import org.springframework.validation.Errors;

    use namespace meta;

    [Managed]
    public class EmployeeRoleBase implements IExternalizable, IUID {

        protected var _em:IEntityManager = null;

        private var __initialized:Boolean = true;
        private var __detachedState:String = null;

        private var _employees:ListCollectionView;
        private var _errors:Errors;
        private var _id:Number;
        private var _roleID:int;
        private var _roleName:String;
        private var _version:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __initialized;

            var property:* = this[name];
            return (
                (!(property is EmployeeRole) || (property as EmployeeRole).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        [Transient]
        public function meta_getEntityManager():IEntityManager {
            return _em;
        }
        public function meta_setEntityManager(em:IEntityManager):void {
        	_em = em;
        }    	
    
    	public static const meta_hasMany:Object = {
			employees: Employee
		}
    
    	public static const meta_constraints:Array = [
    		{ property: "roleName" }, 
    		{ property: "employees",
				association: "oneToMany", bidirectional: "true"
    		}, 
    		{ property: "roleID" }
		]

        public function set employees(value:mx.collections.ListCollectionView):void {
            _employees = value;
        }
        public function get employees():ListCollectionView {
            return _employees;
        }

        public function set errors(value:org.springframework.validation.Errors):void {
            _errors = value;
        }
        public function get errors():Errors {
            return _errors;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        [Id]
        public function get id():Number {
            return _id;
        }

        public function set roleID(value:int):void {
            _roleID = value;
        }
        public function get roleID():int {
            return _roleID;
        }

        public function set roleName(value:String):void {
            _roleName = value;
        }
        public function get roleName():String {
            return _roleName;
        }

        public function set version(value:Number):void {
            _version = value;
        }
        [Version]
        public function get version():Number {
            return _version;
        }

        public function set uid(value:String):void {
            // noop...
        }
        public function get uid():String {
            if (isNaN(_id))
                return UIDUtil.createUID();
            return getQualifiedClassName(this) + "#[" + String(_id) + "]";
        }

        public function meta_merge(em:IEntityManager, obj:*):void {
            var src:EmployeeRoleBase = EmployeeRoleBase(obj);
            __initialized = src.__initialized;
            __detachedState = src.__detachedState;
            if (meta::isInitialized()) {
               	em.meta_mergeExternal(src._employees, _employees, null, this, 'employees', function setter(o:*):void{_employees = o as ListCollectionView});
               	em.meta_mergeExternal(src._errors, _errors, null, this, 'errors', function setter(o:*):void{_errors = o as Errors});
               	em.meta_mergeExternal(src._id, _id, null, this, 'id', function setter(o:*):void{_id = o as Number});
               	em.meta_mergeExternal(src._roleID, _roleID, null, this, 'roleID', function setter(o:*):void{_roleID = o as int});
               	em.meta_mergeExternal(src._roleName, _roleName, null, this, 'roleName', function setter(o:*):void{_roleName = o as String});
               	em.meta_mergeExternal(src._version, _version, null, this, 'version', function setter(o:*):void{_version = o as Number});
            }
            else {
               em.meta_mergeExternal(src._id, _id, null, this, 'id', function setter(o:*):void{_id = o as Number});
            }
        }

        public function readExternal(input:IDataInput):void {
            __initialized = input.readObject() as Boolean;
            __detachedState = input.readObject() as String;
            if (meta::isInitialized()) {
                _employees = input.readObject() as ListCollectionView;
                _errors = input.readObject() as Errors;
                _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _roleID = input.readObject() as int;
                _roleName = input.readObject() as String;
                _version = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
            else {
                _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__initialized);
            output.writeObject(__detachedState);
            if (meta::isInitialized()) { 
                output.writeObject((_employees is IPropertyHolder) ? IPropertyHolder(_employees).object : _employees); 
                output.writeObject((_errors is IPropertyHolder) ? IPropertyHolder(_errors).object : _errors); 
                output.writeObject((_id is IPropertyHolder) ? IPropertyHolder(_id).object : _id); 
                output.writeObject((_roleID is IPropertyHolder) ? IPropertyHolder(_roleID).object : _roleID); 
                output.writeObject((_roleName is IPropertyHolder) ? IPropertyHolder(_roleName).object : _roleName); 
                output.writeObject((_version is IPropertyHolder) ? IPropertyHolder(_version).object : _version);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}
